server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
              - Path=/user/**
    consul:
      config:
        enabled: false
      host: localhost
      port: 8500


